/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algebra.project.view;

import algebra.project.dal.Repository;
import algebra.project.dal.RepositoryFactory;
import algebra.project.dal.parsers.rss.MovieParser;
import algebra.project.model.Movie;
import algebra.project.utils.MessageUtils;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.xml.stream.XMLStreamException;

/**
 *
 * @author Kiki
 */
public class GetMoviesPanel extends javax.swing.JPanel {

    /**
     * Creates new form GetMoviesPanel
     */
    
    private Repository repository;
    private DefaultListModel<Movie> model = new DefaultListModel<>();
    
    public GetMoviesPanel() {
        initComponents();
        initList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMovies = new javax.swing.JList<>();
        btnGetMovies = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1060, 700));

        jScrollPane1.setViewportView(listMovies);

        btnGetMovies.setText("Get movies from internet source");
        btnGetMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetMoviesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(btnGetMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGetMovies, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnGetMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetMoviesActionPerformed
        try {
            List<Movie> movies = MovieParser.parse();
            repository.createAllMovies(movies);
            loadModel();
        } catch (Exception ex ) {
            Logger.getLogger(GetMoviesPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to get movies");
            System.exit(1);
        }
    }//GEN-LAST:event_btnGetMoviesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetMovies;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Movie> listMovies;
    // End of variables declaration//GEN-END:variables

    private void initList() {
        try {
            repository = RepositoryFactory.getRepository();
            model = new DefaultListModel<>();
            loadModel();
        } catch (Exception ex) {
            Logger.getLogger(GetMoviesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadModel() throws Exception {
        model.clear();
        List<Movie> movies = repository.selectAllMovies();
        movies.forEach(model::addElement);
        listMovies.setModel(model);
    }
}
